package com.kgi.shredder.domain.enums;

public enum EventType {
    DOCUMENT_UPLOADED,
    DOCUMENT_VERSION_REPLACED,
    DUPLICATE_DOCUMENT_REJECTED,
    DOCUMENT_SOFT_DELETED,
    VERSION_CREATED,
    JOB_QUEUED,
    JOB_COMPLETED,
    JOB_FAILED,
    PII_REDACTED,
    CHECKPOINT_COMPLETED,
    MODULES_GENERATED,
    DOCUMENT_VECTORIZED,
    RAG_QUERY_EXECUTED,
    MODULE_ATTEMPT_RECORDED,
    DOCUMENT_FEEDBACK_CREATED,
    DOCUMENT_READ_MARKED,
    CHANGE_REQUEST_CREATED,
    INCIDENT_CREATED,
    INCIDENT_RESOLVED
}
